language: node_js

node_js:
  - 16
  - 14
  - 12

cache:
  directories:
    - node_modules

script:
- npm run lint
- npm test
- npx codecov

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true