branches:
  only:
    - master
    - next
    - beta
    - /^\d+\.(\d+|x)(\.x)?$/
  
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release --dry-run
        on:
          all_branches: true